version: "3.9"
services:
  pancake-lottery-bot-local:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/home/app
  mongoapp:
    image: mongo # remember use this as server name on .env
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: